name: Build
description: Build base redis image
inputs:
  version:
    description: redis version
    required: true
  workdir:
    description: working directory
    required: true
  tags:
    description: image tags
    required: true
  alpine_ver:
    description: alpine version
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build image
    env:
      REDIS_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
      ALPINE_VER: ${{ inputs.alpine_ver }}
    run: |
      set -e
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
    working-directory: ${{ inputs.workdir }}/alpine
