name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BASE_IMAGE_STABILITY_TAG: 2.10.6
  REDIS62: '6.2.6'
  REDIS60: '6.0.16'
  REDIS5: '5.0.14'

jobs:
  redis-62:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.REDIS62 }}
        tags: ${{ env.REDIS62 }},6.2,6,latest
        workdir: 6.2
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  redis-6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.REDIS60 }}
        tags: ${{ env.REDIS60 }},6.0
        workdir: '6.0'
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  redis-5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.REDIS50 }}
        tags: ${{ env.REDIS50 }},5.0,5
        workdir: 5
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.15
  redis-62-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.REDIS62 }}
        tags: ${{ env.REDIS62 }}-alpine3.13,6.2-alpine3.13,6-alpine3.13,alpine3.13
        workdir: 6.2
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.13
  redis-6-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.REDIS60 }}
        tags: ${{ env.REDIS60 }}-alpine3.13,6.0-alpine3.13
        workdir: '6.0'
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.13
  redis-5-alpine313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: ${{ env.REDIS50 }}
        tags: ${{ env.REDIS50 }}-alpine3.13,5.0-alpine3.13,5-alpine3.13
        workdir: 5
        platform: linux/amd64,linux/arm64
        alpine_ver: 3.13
