name: Build docker image

on:
  push:
    branches:
    - master

    tags:
    - '*'

  pull_request:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  BASE_IMAGE_STABILITY_TAG: 2.10.6

jobs:
  redis-62:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '6.2.6'
        tags: 6.2.6,6.2,6,latest
        workdir: 6.2
        platform: linux/amd64,linux/arm64
  redis-6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '6.0.16'
        tags: 6.0.16,6.0
        workdir: '6.0'
        platform: linux/amd64,linux/arm64
  redis-5:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
      with:
        version: '5.0.14'
        tags: 5.0.14,5.0,5,latest
        workdir: 5
        platform: linux/amd64,linux/arm64
